on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false
    inputs:
      image_name:
        type: string
        required: false
      checkout_modules:
        type: boolean
        required: false
      test_check:
        type: boolean
        required: false
      npm_registry:
        type: string
        required: false
        default: "https://npm.pkg.github.com"
      directory:
        type: string
        description: "the directory to run the action in"
        required: false
        default: "."

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ inputs.image_name || github.repository }}

jobs:
  checks:
    uses: knallbumm/kb-github-actions/.github/workflows/checks.yml@pnpm
    secrets:
      NPM_TOKEN: ${{secrets.NPM_TOKEN }}
    with:
      test_check: ${{ inputs.test_check }}
      checkout_modules: ${{ inputs.checkout_modules }}
      npm_registry: ${{ inputs.npm_registry }}

  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: checks
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.NPM_TOKEN }}

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@v11.1.1"
        with:
          skip-tag:  'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: ${{ inputs.directory }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ${{ inputs.directory }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=prod,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=dev,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
            type=ref,event=branch
            type=raw,value=${{ steps.package-version.outputs.current-version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ inputs.directory}}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
