on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false
    inputs:
      checkout_modules:
        type: boolean
        required: false
      test_check:
        type: boolean
        required: false
      npm_registry:
        type: string
        required: false
        default: "https://npm.pkg.github.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: prepare node
        uses: knallbumm/kb-github-actions/.github/actions/prepare-node@pnpm
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          checkout_modules: ${{ inputs.checkout_modules }}
          npm_registry: ${{ inputs.npm_registry }}

      - name: run build
        run: pnpm run build

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: prepare node
        uses: knallbumm/kb-github-actions/.github/actions/prepare-node@pnpm
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          checkout_modules: ${{ inputs.checkout_modules }}
          npm_registry: ${{ inputs.npm_registry }}

      - name: run linting
        run: pnpm run lint

  type:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: prepare node
        uses: knallbumm/kb-github-actions/.github/actions/prepare-node@pnpm
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          checkout_modules: ${{ inputs.checkout_modules }}
          npm_registry: ${{ inputs.npm_registry }}

      - name: run typecheck
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.test_check == true }}
    timeout-minutes: 10
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: prepare node
        uses: knallbumm/kb-github-actions/.github/actions/prepare-node@pnpm
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          checkout_modules: ${{ inputs.checkout_modules }}
          npm_registry: ${{ inputs.npm_registry }}

      - name: run tests
        run: pnpm run test
